include: package:flutter_lints/flutter.yaml
analyzer: 
   errors: 
    unused_import: ignore
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true  
