name: tiktok_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  better_player_plus: ^1.0.8
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  supabase_flutter: ^2.9.0
  uuid: ^4.5.1
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  image_path: "assets/icon_lanuch/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon_lanuch/
    - assets/vedios/
    - .env
